import { Config, Inputs } from "./types.js";

export const getConfig = (inputs: Inputs): Config => {
  return {
    bot: {
      username: "Netlify",
      avatarUrl: "https://www.netlify.com/v3/static/favicon/icon-512.png",
      ...inputs.bot,
    },
    success: {
      disabled: false,
      title: "Build deployed",
      status: "deployed",
      color: 0x1f8b4c,
      showBuildId: true,
      showContext: true,
      showBranch: true,
      showCommit: true,
      showDiff: true,
      showLogs: true,
      ...inputs.success,
    },
    error: {
      disabled: false,
      title: "Build failed",
      status: "failed to deploy",
      color: 0x992d22,
      showBuildId: true,
      showContext: true,
      showBranch: true,
      showCommit: true,
      showDiff: true,
      showLogs: true,
      ...inputs.error,
    },
    preBuild: {
      disabled: true,
      title: "Build started",
      status: "build started",
      color: 0x3498db,
      ...inputs.preBuild,
    },
    build: {
      disabled: true,
      title: "Building",
      status: "building",
      color: 0x3498db,
      ...inputs.build,
    },
    postBuild: {
      disabled: true,
      title: "Build finished",
      status: "build finished",
      color: 0x3498db,
      ...inputs.postBuild,
    },
    end: {
      disabled: true,
      title: "Build ended",
      status: "build ended",
      color: 0x3498db,
      ...inputs.end,
    },
    preDev: {
      disabled: true,
      title: "Dev init",
      status: "dev init",
      color: 0x3498db,
      showBuildId: false,
      showContext: false,
      showBranch: false,
      showCommit: false,
      showDiff: false,
      showLogs: false,
      ...inputs.preDev,
    },
    dev: {
      disabled: true,
      title: "Dev started",
      status: "dev started",
      color: 0x3498db,
      showBuildId: false,
      showContext: false,
      showBranch: false,
      showCommit: false,
      showDiff: false,
      showLogs: false,
      ...inputs.dev,
    },
  };
};
